dataset: stl10
data_root: data
img_size: 224
eval_split: test

ckpt_path: experiments/mae_pretrained/mae_stl10_vit_tiny_mask75_dec4.pth

patch_size: 16
embed_dim: 192
encoder_depth: 12
encoder_heads: 3
encoder_mlp_ratio: 4.0
dropout: 0.0

pool: cls
batch_size: 256
epochs: 50
lr: 0.1
momentum: 0.9
weight_decay: 0.0
num_workers: 8

output_dir: experiments/linear_probe
run_name: lprobe_stl10_mask75_dec4_cls

use_wandb: true
wandb_project: mae-compact
wandb_run_name: lprobe_stl10_mask75_dec4_cls
wandb_tags: ["linear_probe", "stl10", "mask75", "dec4"]
wandb_mode: offline

